FROM node:18-alpine
WORKDIR /app

# expect a bind mount to be mounted at /app
EXPOSE 5173

VOLUME /app/node_modules

RUN corepack enable

# we can't pack dependencies or bind them as
# the platform of the host and the container
# are not the same.
CMD yarn && yarn dev --host 0.0.0.0 --strictPort --force
