FROM node:18-alpine
RUN adduser -D -s /bin/sh -u 1001 app
RUN corepack enable
USER app

WORKDIR /app
COPY --chown=app:app .yarnrc.yml package.json yarn.lock .
RUN yarn install


# Copy source files into application directory
COPY --chown=app:app . /app/

EXPOSE 5173

# We use Compose in watch mode.
CMD yarn dev --host 0.0.0.0 --strictPort --force
