name: bounswe2024group1-dev

services:
  swagger:
    extends:
      file: compose.yml
      service: swagger
  db:
    extends:
      file: compose.yml
      service: db
    volumes:
      - db-data:/var/lib/mysql
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile.dev
    platform: linux/amd64
    volumes:
      - ./backend:/app
    environment:
      DB_HOST: db
      DB_NAME: cuisines-test
      DB_USER: root
      DB_PASSWORD: admin
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - db
  web:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.dev
    environment:
      - PROXY_API=http://backend:8080
    ports:
      - "5173:5173"
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - ./frontend/node_modules/
        - action: rebuild
          path: ./frontend/package.json
volumes:
  node_modules:
  db-data:
