version: "3.3"
name: bounswe2024group1-dev

services:
  swagger-dev:
    image: swaggerapi/swagger-ui
    environment:
      SWAGGER_JSON: /openapi.yaml
    volumes:
      - ./swagger/openapi.yml:/openapi.yaml
    ports:
      - "8081:8080"
  db-dev:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: "cuisines-test"
      MYSQL_ROOT_PASSWORD: "admin"
    ports:
      - "3306:3306"
    volumes:
      - db-data-dev:/var/lib/mysql
  backend-dev:
    build:
      context: ./backend
      dockerfile: ./Dockerfile.dev
    platform: linux/amd64
    volumes:
      - ./backend:/app
    environment:
      DB_HOST: db-dev
      DB_NAME: cuisines-test
      DB_USER: root
      DB_PASSWORD: admin
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - db-dev
  web-dev:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.dev
    environment:
      - PROXY_API=http://backend-dev:8080
    ports:
      - "5173:5173"
    volumes:
      - node_modules:/app/node_modules
      - ./frontend:/app

volumes:
  node_modules:
  db-data-dev:
