version: "3.1"
# Production-like docker-compose setup

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: "cuisines-test"
      MYSQL_ROOT_PASSWORD: "admin"
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
  backend:
    build: ./backend
    platform: linux/amd64
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_NAME: cuisines-test
      DB_USER: root
      DB_PASSWORD: admin
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - db
  web:
    platform: linux/amd64
    build: ./frontend
    volumes:
      # these binds are required to reverse proxy the backend through nginx
      # in prod, this is configured through digitalocean
      - ./frontend/nginx/nginx-docker-compose.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/nginx/template-vars.conf:/etc/nginx/templates/10-variables.conf.template
    environment:
      - PROXY_API=http://backend:8080
    ports:
      - "80:80"

volumes:
  db-data:
