services:
  backend:
    build: !reset null
    image: stoplight/prism
    volumes:
      - ./swagger/openapi.yml:/usr/src/prism/spec.yml
    command: "mock /usr/src/prism/spec.yml -h 0.0.0.0 -p 8080"
  web:
    environment:
      - PROXY_REMOVE_BASE_PATH=1
