alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
features:
  - buildpack-stack=ubuntu-22
ingress:
  rules:
    - component:
        name: backend
        preserve_path_prefix: true
      match:
        path:
          prefix: /api
    - component:
        name: web
      match:
        path:
          prefix: /
name: programming-languages-staging
region: fra
databases:
  - name: programming-languages
    engine: MYSQL
    version: "8.0"
    production: true
    cluster_name: programmingforum-staging
    db_name: programmingforum
    db_user: programmingforum
services:
  - envs:
      - key: DB_HOST
        scope: RUN_AND_BUILD_TIME
        value: ${db.HOSTNAME}:${db.PORT}
      - key: DB_NAME
        scope: RUN_AND_BUILD_TIME
        value: ${db.DATABASE}
      - key: DB_USER
        scope: RUN_AND_BUILD_TIME
        value: ${db.USERNAME}
      - key: DB_PASSWORD
        scope: RUN_AND_BUILD_TIME
        value: ${db.PASSWORD}
      - key: SPRING_PROFILES_ACTIVE
        scope: RUN_AND_BUILD_TIME
        value: docker
    http_port: 8080
    image:
      deploy_on_push:
        enabled: true
      registry_type: DOCR
      repository: backend
      tag: staging
    instance_count: 1
    instance_size_slug: professional-xs
    name: backend
  - http_port: 80
    image:
      deploy_on_push:
        enabled: true
      registry_type: DOCR
      repository: web
      tag: staging
    instance_count: 1
    instance_size_slug: professional-xs
    name: web
