/**
 * Generated by @openapi-codegen
 *
 * @version 1.0.0
 */
import type * as Schemas from "./programmingForumSchemas";

export type BadRequestResponse = Schemas.ErrorResponseObject;

export type UnauthorizedResponse = Schemas.ErrorResponseObject;

export type ForbiddenResponse = Schemas.ErrorResponseObject;

export type NotFoundResponse = Schemas.ErrorResponseObject;

export type TooManyRequestsResponse = Schemas.ErrorResponseObject;
