/**
 * Generated by @openapi-codegen
 *
 * @version 1.0.3
 */
export type UserRegistration = {
  email: string;
  username: string;
  password: string;
  bio?: string;
  firstName: string;
  lastName: string;
  country: string;
};

export type UserLogin = {
  usernameOrEmail: string;
  password: string;
};

export type AuthToken = {
  token?: string;
};

/**
 * @example {"id":1,"username":"takoyaki_lover","name":"Takoyaki Lover","bio":"I love takoyaki!","followersCount":100,"gender":"unknown","profilePicture":"https://images.unsplash.com/photo-1633790450512-98e68a55ef15?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&dl=brunno-tozzo-GAIC2WHxm5A-unsplash.jpg&w=640","diets":["keto"],"recipeCount":10,"bookmarks":[{"id":1,"name":"My Takoyaki Recipe","description":"A delicious takoyaki recipe that I learned from my grandmother.","cookTime":30,"images":["http://commons.wikimedia.org/wiki/Special:FilePath/Takoyaki%20by%20yomi955.jpg"],"rating":4.5,"dish":{"id":"http://www.wikidata.org/entity/Q905527","name":"takoyaki"}}],"recipes":[{"id":1,"name":"My Takoyaki Recipe","description":"A delicious takoyaki recipe that I learned from my grandmother.","cookTime":30,"images":["http://commons.wikimedia.org/wiki/Special:FilePath/Takoyaki%20by%20yomi955.jpg"],"rating":4.5,"dish":{"id":"http://www.wikidata.org/entity/Q905527","name":"takoyaki"}}]}
 */
export type UserProfile = {
  id?: number;
  username?: string;
  name?: string;
  bio?: string;
  followersCount?: number;
  gender?: "male" | "female" | "unknown";
  /**
   * @format uri
   */
  profilePicture?: string;
  diets?: string[];
  recipeCount?: number;
  /**
   * Only available when querying the current user's profile.
   */
  bookmarks?: RecipeSummary[];
  recipes?: RecipeSummary[];
};

/**
 * @example {"id":1,"username":"takoyaki_lover","name":"Takoyaki Lover","followersCount":100,"profilePicture":"http://commons.wikimedia.org/wiki/Special:FilePath/Takoyaki%20by%20yomi955.jpg","recipeCount":10,"avgRating":4.5}
 */
export type UserSummary = {
  id: number;
  username: string;
  name: string;
  followersCount: number;
  /**
   * @format uri
   */
  profilePicture: string;
  recipeCount: number;
  /**
   * @format float
   */
  avgRating: number;
};

/**
 * @example {"id":"http://www.wikidata.org/entity/Q905527","name":"takoyaki","description":"ball-shaped Japanese snack with octopus","image":"http://commons.wikimedia.org/wiki/Special:FilePath/Takoyaki%20by%20yomi955.jpg","countries":"Japan","ingredients":"wheat flour, green laver, octopus as food, beni shōga, katsuobushi, Welsh onion","foodTypes":"konamono, octopus dish, yakimono","cuisines":"Japanese cuisine"}
 */
export type DishDetails = {
  id: string;
  name: string;
  description: string;
  /**
   * @format uri
   */
  image: string;
  countries: string;
  ingredients?: string;
  foodTypes?: string;
  cuisine?: CuisineSummary;
  /**
   * Only returned when directly querying a dish.
   */
  recipes?: RecipeSummary[];
};

export type CuisineDetails = {
  id: string;
  name: string;
  description: string;
  /**
   * @format uri
   */
  image: string;
  isSelfFollowing?: boolean;
  dishes?: DishSummary[];
};

/**
 * @example {"id":1,"name":"My Takoyaki Recipe","description":"A delicious takoyaki recipe that I learned from my grandmother.","cookTime":30,"images":["http://commons.wikimedia.org/wiki/Special:FilePath/Takoyaki%20by%20yomi955.jpg"],"avgRating":4.5,"ratingsCount":42,"selfRating":5,"dish":{"id":"http://www.wikidata.org/entity/Q905527","name":"takoyaki","image":"http://commons.wikimedia.org/wiki/Special:FilePath/Takoyaki%20by%20yomi955.jpg"},"author":{"id":1,"username":"takoyaki_lover","name":"Takoyaki Lover","followersCount":100,"profilePicture":"http://commons.wikimedia.org/wiki/Special:FilePath/Takoyaki%20by%20yomi955.jpg","recipeCount":10,"avgRating":4.5}}
 */
export type RecipeSummary = {
  id: number;
  name: string;
  description: string;
  /**
   * Cook time in minutes
   */
  cookTime: number;
  images: string[];
  /**
   * @format float
   */
  avgRating?: number;
  ratingsCount: number;
  selfRating?: number;
  dish: DishSummary;
  author: UserSummary;
};

/**
 * @example {"id":1,"name":"My Takoyaki Recipe","description":"A delicious takoyaki recipe that I learned from my grandmother.","instructions":["Mix the batter.","Add the octopus.","Cook the takoyaki balls."],"ingredients":["wheat flour","green laver","octopus as food","beni shōga","katsuobushi","Welsh onion"],"images":["http://commons.wikimedia.org/wiki/Special:FilePath/Takoyaki%20by%20yomi955.jpg"],"cookTime":"30 minutes","servingSize":4,"allergens":["seafood"],"cuisine":{"id":1,"name":"Japanese"},"dish":{"id":"http://www.wikidata.org/entity/Q905527","name":"takoyaki","image":"http://commons.wikimedia.org/wiki/Special:FilePath/Takoyaki%20by%20yomi955.jpg"},"avgRating":4.5,"ratingsCount":10}
 */
export type RecipeDetails = {
  id: number;
  name: string;
  description: string;
  instructions: string[];
  ingredients: string[];
  images: string[];
  cookTime: number;
  servingSize: number;
  allergens: string[];
  cuisine?: CuisineSummary;
  dish: DishSummary;
  /**
   * @format float
   */
  avgRating?: number;
  ratingsCount: number;
  /**
   * The current user's rating for this recipe, if any.
   */
  selfRating?: number;
  author: UserSummary;
};

/**
 * @example {"name":"My Takoyaki Recipe","description":"A delicious takoyaki recipe that I learned from my grandmother.","instructions":["Mix the batter.","Add the octopus.","Cook the takoyaki balls."],"ingredients":["wheat flour","green laver","octopus as food","beni shōga","katsuobushi","Welsh onion"],"images":["http://commons.wikimedia.org/wiki/Special:FilePath/Takoyaki%20by%20yomi955.jpg"],"prepTime":"10 minutes","cookTime":"30 minutes","servingSize":4,"allergens":["seafood"],"dishId":1}
 */
export type NewRecipe = {
  name: string;
  description?: string;
  instructions: string[];
  ingredients: string[];
  images?: Blob[];
  prepTime: string;
  cookTime: string;
  servingSize: number;
  allergens?: string[];
  dishId?: number;
};

/**
 * @example {"id":1,"name":"Japanese"}
 */
export type CuisineSummary = {
  id: number;
  name: string;
};

/**
 * @example {"id":1,"name":"takoyaki"}
 */
export type DishSummary = {
  id: number;
  name: string;
};

export type Comment = {
  id: number;
  author: UserSummary;
  recipeId?: number;
  upvoteCount: number;
  content: string;
  hasSelfUpvoted: boolean;
  /**
   * @format date-time
   */
  createdAt: string;
};

/**
 * An array of comments
 */
export type CommentArray = Comment[];

/**
 * An array of dishes
 */
export type DishArray = DishDetails[];

/**
 * An array of recipes
 */
export type RecipeArray = RecipeDetails[];

/**
 * An array of users
 */
export type UserArray = UserSummary[];

/**
 * @example {"status":200,"data":{"message":"Success"}}
 * @example {"status":400,"errors":[{"message":"Invalid email","field":"email"},{"message":"Invalid password","field":"password"}]}
 */
export type ApiResponse = SuccessResponseObject | ErrorResponseObject;

export type ApiError = {
  message: string;
  /**
   * If empty, indicates an error not related to any field.
   */
  field?: string;
};

/**
 * OK
 */
export type SuccessResponseObject = {
  /**
   * Internal status code of the response. An HTTP 200 response with an internal 500 status code is an error response. Prioritize the inner status over the HTTP status.
   *
   * @example 200
   * @example 201
   */
  status: 200 | 201;
  data: Record<string, any> | any[];
};

/**
 * Response with errors
 */
export type ErrorResponseObject = {
  /**
   * Internal status code of the response. An HTTP 200 response with an internal 500 status code is an error response. Prioritize the inner status over the HTTP status.
   *
   * @example 400
   * @example 401
   * @example 403
   * @example 404
   * @example 409
   * @example 500
   */
  status: 400 | 401 | 403 | 404 | 409 | 500;
  errors: ApiError[];
};
