alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
features:
  - buildpack-stack=ubuntu-22
ingress:
  rules:
    - component:
        name: backend
        preserve_path_prefix: true
      match:
        path:
          prefix: /api
    - component:
        name: web
      match:
        path:
          prefix: /
name: semantic-cuisine
region: fra
services:
  - envs:
      - key: DB_HOST
        scope: RUN_AND_BUILD_TIME
        value: 157.230.112.13
      - key: DB_NAME
        scope: RUN_AND_BUILD_TIME
        value: cuisines
      - key: DB_USER
        scope: RUN_AND_BUILD_TIME
        value: cuisines
      - key: DB_PASSWORD
        scope: RUN_AND_BUILD_TIME
        type: SECRET
        value: EV[1:u0xWINYBTwxD3rXhMDFhi2OBoBXyeTrJ:07XRzmcL+Hd7OYHHKS4GGcgrMxjbi4d2hOxD3+vB0Q==]
      - key: SPRING_PROFILES_ACTIVE
        scope: RUN_AND_BUILD_TIME
        value: docker
    http_port: 8080
    image:
      deploy_on_push:
        enabled: true
      registry_type: DOCR
      repository: backend
      tag: latest
    instance_count: 1
    instance_size_slug: professional-xs
    name: backend
  - http_port: 80
    image:
      deploy_on_push:
        enabled: true
      registry_type: DOCR
      repository: web
      tag: latest
    instance_count: 1
    instance_size_slug: professional-xs
    name: web
