alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: backend
      preserve_path_prefix: true
    match:
      path:
        prefix: /api
  - component:
      name: web
    match:
      path:
        prefix: /
name: semantic-cuisine-staging
region: fra
services:
- envs:
  - key: DB_HOST
    scope: RUN_AND_BUILD_TIME
    value: 209.38.248.150
  - key: DB_NAME
    scope: RUN_AND_BUILD_TIME
    value: cuisines
  - key: DB_USER
    scope: RUN_AND_BUILD_TIME
    value: cuisines
  - key: SPRING_PROFILES_ACTIVE
    scope: RUN_AND_BUILD_TIME
    value: docker
  - key: DB_PASSWORD
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:m2QNrJThHgB8l0Y8m3IvGaCg5kUELAZi:bpO4AU4KJ7L+UfRRh2q2lq9CNvaGBxSxhz9hBWXy3w==]
  http_port: 8080
  image:
    deploy_on_push:
      enabled: true
    registry_type: DOCR
    repository: backend-staging
    tag: latest
  instance_count: 1
  instance_size_slug: professional-xs
  name: backend
- http_port: 80
  image:
    deploy_on_push:
      enabled: true
    registry_type: DOCR
    repository: web-staging
    tag: latest
  instance_count: 1
  instance_size_slug: professional-xs
  name: web
